spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8769
zuul:
  routes:
    api-a:
      path: /aquarius/web/**
      serviceId: Aquarius-home-web
      sensitive-headers:
      custom-sensitive-headers: true
    api-b:
      path: /aquarius/api/**
      serviceId: aquarius-sso-services
      sensitive-headers:
      custom-sensitive-headers: true