spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8769
zuul:
  sensitive-headers: "*"
  routes:
    api-a:
      path: /aquarius/web/**
      serviceId: Aquarius-home-web
    api-b:
      path: /aquarius/api/**
      serviceId: aquarius-sso-services
    api-c:
      path: /aquarius/api/**
      serviceId: aquarius-user-main-services
