spring:
  application:
    name: aquarius-upload-services

server:
  port: 8505

tencentinfo:
  secretId: AKIDLWTChyfoNineFayU3NRHuISQ8i29tf29
  secretKey: 3rRknbASe7OQFpBNPEoCMIzVmpdDZooZ
  regionzon: ap-guangzhou
  bucketNames:
    avatarbucketName: avatars-1257722515
    videobucketName: videos-1257722515
    mypicturesbucketName: mypictures-1257722515

