spring:
  application:
    name: Aquarius-home-web
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-request-size: 2500MB
      file-size-threshold: 2000MB

server:
  port: 8601



